import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';

import 'package:distance/shared/motion.dart';

/// Lottie animations generated by `tool/generate_lottie.dart`.
abstract final class Illustrations {
  static const loading = 'assets/lottie/loading.json';
  static const empty = 'assets/lottie/empty.json';
  static const error = 'assets/lottie/error.json';
  static const success = 'assets/lottie/success.json';
}

/// A looping Lottie illustration. It plays once when ambient motion is off
/// and stays on its first frame when the device asks to reduce motion.
/// Decorative: the text next to it carries the meaning.
class LottieIllustration extends StatelessWidget {
  const LottieIllustration(this.asset, {super.key, this.size = 200});

  final String asset;
  final double size;

  @override
  Widget build(BuildContext context) {
    return ExcludeSemantics(
      child: Lottie.asset(
        asset,
        width: size,
        height: size,
        animate: !MediaQuery.disableAnimationsOf(context),
        repeat: AmbientMotion.enabled,
        // Smoother than the 60 fps the files are authored at, on 90/120 Hz
        // screens.
        frameRate: FrameRate.max,
      ),
    );
  }
}

/// One-shot celebration: a badge with a check pops in, holds for a moment
/// and fades away. Give it a new key to play it again.
class SuccessBurst extends StatefulWidget {
  const SuccessBurst({super.key, this.size = 180});

  final double size;

  @override
  State<SuccessBurst> createState() => _SuccessBurstState();
}

class _SuccessBurstState extends State<SuccessBurst>
    with TickerProviderStateMixin {
  late final AnimationController _play = AnimationController(vsync: this);

  /// Hold, then fade out once the animation has played.
  late final AnimationController _fade = AnimationController(
    vsync: this,
    duration: const Duration(milliseconds: 900),
  );
  late final Animation<double> _opacity = Tween<double>(begin: 1, end: 0)
      .animate(
        CurvedAnimation(
          parent: _fade,
          curve: const Interval(0.5, 1, curve: Curves.easeIn),
        ),
      );

  @override
  void initState() {
    super.initState();
    _play.addStatusListener((status) {
      if (status == AnimationStatus.completed) _fade.forward();
    });
  }

  void _onLoaded(LottieComposition composition) {
    _play.duration = composition.duration;
    if (MediaQuery.disableAnimationsOf(context)) {
      // Straight to the finished badge.
      _play.value = 1;
    } else {
      _play.forward();
    }
  }

  @override
  void dispose() {
    _play.dispose();
    _fade.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return IgnorePointer(
      child: ExcludeSemantics(
        child: AnimatedBuilder(
          animation: _fade,
          builder: (context, child) => _fade.isCompleted
              ? const SizedBox.shrink()
              : Opacity(opacity: _opacity.value, child: child),
          child: Lottie.asset(
            Illustrations.success,
            controller: _play,
            onLoaded: _onLoaded,
            width: widget.size,
            height: widget.size,
            frameRate: FrameRate.max,
          ),
        ),
      ),
    );
  }
}
